spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feng?serverTimezone=UTC
    username: fengyizhou
    password: 2003
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 6094

file:
  upload:
    path: /www/server/tomcat8/webapps/files/

# 时间2024/02/24 13:15 结束 我们何时才能再见面